# Generated by Django 5.2.7 on 2025-10-23 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.CharField(choices=[('PERSONAL PROBLEMS', 'PERSONAL PROBLEMS'), ('FAMILY PROBLEMS', 'FAMILY PROBLEMS'), ('DEPRESSION', 'DEPRESSION')], max_length=50),
        ),
    ]
