# Generated by Django 5.2.7 on 2025-10-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_sample_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_id',
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
